name: "GitHub Page: Build and Deploy"

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  github-page:
    uses: seanox/seanox-automation/.github/workflows/github-page-update.yaml@1.x
    with:
      includes: |
        manuals
        release
        tutorials
        CHANGES
        README.md
