name: Build & Deploy GitHub Page
on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          find . -type f -name "*.md" -print0 |
          while IFS= read -r -d '' file; do
            sed -E 's/(\{\{.*?\}\})/{% raw %}\1{% endraw %}/g' "$file" > "$file.tmp" \
                && mv "$file.tmp" "$file"
          done
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - run: |
          gem install jekyll
      - run: |
          jekyll build --source ./ --destination _site
      - uses: actions/upload-pages-artifact@v5
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v5
