name: "GitHub Page: Build and Deploy"

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  github-page:
    uses: seanox/seanox-automation/workflows/github-page-update.yaml@1.x
