name: "on-dispatch: Build and Deploy GitHub Page"

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Protect Liquid expressions in Markdown
        run: |
          find . -type f -name "*.md" -print0 |
          while IFS= read -r -d '' file; do
            sed -E 's/(\{\{.*?\}\})/{% raw %}\1{% endraw %}/g' "$file" > "$file.tmp" &&
            mv "$file.tmp" "$file"
          done

      - name: Create temporary Gemfile
        run: |
          cat > Gemfile <<'EOF'
          source "https://rubygems.org"

          gem "github-pages", group: :jekyll_plugins
          EOF

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Build Jekyll site
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          echo "url: \"https://${GITHUB_REPOSITORY_OWNER}.github.io\"" > _config.yml
          echo "baseurl: \"/${REPO_NAME}\"" >> _config.yml
          cat _config.yml          
          bundle exec jekyll build --source ./ --destination _site

      - uses: actions/upload-pages-artifact@v5
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/deploy-pages@v5
